name: GitHub-Profile-Summary-Cards

on:
  create:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs: uwu
build:
  runs-on: ubuntu-latest
  name: generate-github-cards
  permissions:
    contents: write

  steps:
    - uses: actions/checkout@v2
    - uses: vn7n24fzkq/github-profile-summary-cards@release
      env:
        GITHUB_TOKEN: ${{ secrets.[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] }}
      with:
        USERNAME: ${{ Lumikin/Lumikin }}
